[package]
name = "xmss"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
p3-koala-bear.workspace = true
rand.workspace = true
utils.workspace = true
p3-symmetric.workspace = true
p3-util.workspace = true